# fly.toml app configuration file generated for simplehttp4kserver-pedro on 2025-04-07T14:15:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simplehttp4kserver-pedro'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8124
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
